[Head]
"Current Version" = "GitHub build 500, built on 2026-08-09 from commit 8e11304"
"Latest Version" = "GitHub build 500, built on 2026-08-09"

[Main]
[Main.General]
Account = { Login = "Lervy_Lever", Password = "-" }
Server = { Host = "play.amorycraft.com" }
AccountType = "mojang"
Method = "mcc"

[Main.Advanced]
EnableSentry = false
Language = "en_us"
LoadMccTranslation = false
LoadResourcePackTranslations = false
LoadForgeModTranslations = false
AutoDiscoverForgeModTranslationSources = false
ForgeModTranslationPath = ""
ConsoleTitle = "%username%@%serverip% - Minecraft Console Client"
InternalCmdChar = "slash"
MessageCooldown = 1.0
MaxChatMessageLength = 100
BotOwners = [ ]
MinecraftVersion = "auto"
EnableForge = "no"
BrandInfo = "mcc"
ChatbotLogFile = ""
PrivateMsgsCmdName = "tell"
ShowSystemMessages = false
ShowXPBarMessages = false
ShowChatLinks = false
ShowInventoryLayout = false
ShowEffectMessages = false
ShowEffectNamesInTUI = false
ShowGithubStarReminder = false
TerrainAndMovements = false
MoveHeadWhileWalking = false
MovementSpeed = 2
TemporaryFixBadpacket = false
InventoryHandling = true
EntityHandling = false
SessionCache = "none"
ProfileKeyCache = "none"
ResolveSrvRecords = "fast"
PlayerHeadAsIcon = false
ExitOnFailure = false
CacheScript = false
Timestamps = false
AutoRespawn = false
MinecraftRealms = false
TcpTimeout = 30
EnableEmoji = false
MinTerminalWidth = 16
MinTerminalHeight = 10
IgnoreInvalidPlayerName = true

[Signature]
LoginWithSecureProfile = false
SignChat = false
SignMessageInCommand = false
MarkLegallySignedMsg = false
MarkModifiedMsg = false
MarkIllegallySignedMsg = false
MarkSystemMessage = false
ShowModifiedChat = false
ShowIllegalSignedChat = false

[Logging]
DebugMessages = false
PacketDebugMessages = false
PacketDebugExclusions = [ ]
ChatMessages = false
InfoMessages = false
WarningMessages = false
ErrorMessages = true
ChatFilterRegex = ".*"
DebugFilterRegex = ".*"
FilterMode = "disable"
LogToFile = false
LogFile = "console-log.txt"
PrependTimestamp = false
SaveColorCodes = false

[Console]
[Console.General]
ConsoleMode = "classic"
ConsoleColorMode = "disable"
Display_Icon_Banner = false
Display_Input = false
Display_Chat = false
History_Input_Records = 0
TUI_Log_Scrollback = 0

[Console.CommandSuggestion]
Enable = false

[Console.Minimap]
Enabled = false

[Console.TabList]
ShowTeams = false

[MCSettings]
Enabled = true
Locale = "en_US"
RenderDistance = 2
Difficulty = "peaceful"
ChatMode = "disabled"
ChatColors = false
MainHand = "left"

[MCSettings.Skin]
Cape = false
Hat = false
Jacket = false
Sleeve_Left = false
Sleeve_Right = false
Pants_Left = false
Pants_Right = false

[ChatFormat]
Builtins = false
UserDefined = false

[ChatBot]
[ChatBot.Alerts]
Enabled = false
[ChatBot.AntiAFK]
Enabled = false
[ChatBot.AutoAttack]
Enabled = false
[ChatBot.AutoCraft]
Enabled = false
[ChatBot.AutoDig]
Enabled = false
[ChatBot.AutoDrop]
Enabled = false
[ChatBot.AutoEat]
Enabled = false
[ChatBot.AutoFishing]
Enabled = false
[ChatBot.AutoRelog]
Enabled = false
[ChatBot.AutoRespond]
Enabled = false
[ChatBot.ChatLog]
Enabled = false
[ChatBot.DiscordBridge]
Enabled = false
[ChatBot.Farmer]
Enabled = false
[ChatBot.FollowPlayer]
Enabled = false
[ChatBot.HangmanGame]
Enabled = false
[ChatBot.Mailer]
Enabled = false
[ChatBot.Map]
Enabled = false
[ChatBot.PlayerListLogger]
Enabled = false
[ChatBot.RemoteControl]
Enabled = false
[ChatBot.ReplayCapture]
Enabled = false

# ⚡ เปิดใช้งาน ScriptScheduler
[ChatBot.ScriptScheduler]
Enabled = false
TasksFile = "tasks.ini"

[ChatBot.TelegramBridge]
Enabled = false
[ChatBot.ItemsCollector]
Enabled = false
[ChatBot.DiscordRpc]
Enabled = false
[ChatBot.McpServer]
Enabled = false